version: '3.3'
services:
  #REDIS 
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - casper-info
  # MONGODB
  mongodb:
    image: mongo:6.0.1
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - ./.env
    volumes:
      - mongodbdata:/data/db
    networks:
      - casper-info
  # Main Server
  main-server:
    container_name: main-server
    build: .
    ports:
      - 5001:5001
    env_file:
      - ./.env
    environment:
      - PORT=5001
      - INDEXER=false
      - NODE_ENV=prod
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    networks:
      - casper-info
  indexer-1:
    container_name: indexer-1
    build: .
    ports:
      - 6001:6001
    env_file:
      - ./.env
    environment:
      - PORT=6001
      - INDEXER=true
      - START_BLOCK=1070618
      - END_BLOCK=1120618
      - NODE_ENV=prod
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    networks:
      - casper-info
  block-query:
    container_name: block-query
    build: .
    ports:
      - 6002:6002
    env_file:
      - ./.env
    environment:
      - PORT=6002
      - INDEXER=true
      - NODE_ENV=prod
      # - START_BLOCK=999999
      # - END_BLOCK=950000
      - WORKER_TYPE=BLOCK_QUERY
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    networks:
      - casper-info
  block-save:
    container_name: block-save
    build: .
    ports:
      - 6003:6003
    env_file:
      - ./.env
    environment:
      - PORT=6003
      - INDEXER=true
      - NODE_ENV=prod
      - WORKER_TYPE=BLOCK_SAVE
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    networks:
      - casper-info
  deploy-query:
    container_name: deploy-query
    build: .
    ports:
      - 6004:6004
    env_file:
      - ./.env
    environment:
      - PORT=6004
      - INDEXER=true
      - NODE_ENV=prod
      - WORKER_TYPE=DEPLOY_QUERY
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    networks:
      - casper-info
  era-summary-query:
    container_name: era-summary-query
    build: .
    ports:
      - 6005:6005
    env_file:
      - ./.env
    environment:
      - PORT=6005
      - INDEXER=true
      - NODE_ENV=prod
      - WORKER_TYPE=ERA_SUMMARY_AND_PERFORMANCE_CALCULATION
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    networks:
      - casper-info
  account-update:
    container_name: account-update
    build: .
    ports:
      - 6006:6006
    env_file:
      - ./.env
    environment:
      - PORT=6006
      - INDEXER=true
      - NODE_ENV=prod
      - WORKER_TYPE=ACCOUNT_UPDATE
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
    networks:
      - casper-info
networks:
  casper-info:
volumes:
  mongodbdata:
    
  